[package]
name = "world_builder"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared" }
anyhow.workspace = true
serde.workspace = true
sqlx.workspace = true
time.workspace = true
tokio.workspace = true
thiserror = "1"
